services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: moveapps
      POSTGRES_PASSWORD: moveapps
      POSTGRES_DB: component_repository
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

volumes:
  postgres_data: