"""add format_label column to parameters

Revision ID: 0698c9080d01
Revises: f9618993ab3a
Create Date: 2026-08-06 17:13:22.793200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0698c9080d01'
down_revision: Union[str, Sequence[str], None] = 'f9618993ab3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameters', sa.Column('format_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parameters', 'format_label')
    # ### end Alembic commands ###
