"""add workflow_drafts table

Revision ID: 1eaa140fe000
Revises: e418bb5aa5aa
Create Date: 2026-09-06 12:04:51.560668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1eaa140fe000'
down_revision: Union[str, Sequence[str], None] = 'e418bb5aa5aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('canvas_state', sa.Text(), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # every read of this table is "my drafts, newest first" - the composite index serves
    # both the owner filter and the ordering in one scan
    op.create_index(
        op.f('ix_workflow_drafts_created_by_id'),
        'workflow_drafts',
        ['created_by_id', 'updated_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_drafts_created_by_id'), table_name='workflow_drafts')
    op.drop_table('workflow_drafts')
    # ### end Alembic commands ###
