"""add cwl_type and dockerfile_content columns to components

Revision ID: 3b45a0a8737c
Revises: cd558eeb5fd4
Create Date: 2026-08-12 09:38:27.848877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3b45a0a8737c'
down_revision: Union[str, Sequence[str], None] = 'cd558eeb5fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('cwl_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('components', sa.Column('dockerfile_content', sa.Text(), nullable=True))
    op.add_column('components', sa.Column('ontology_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('components', 'ontology_url')
    op.drop_column('components', 'dockerfile_content')
    op.drop_column('components', 'cwl_type')
    # ### end Alembic commands ###
