"""add source and draft_id to workflows

Revision ID: 5b88e4260cae
Revises: 1eaa140fe000
Create Date: 2026-09-06 14:49:35.426018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b88e4260cae'
down_revision: Union[str, Sequence[str], None] = '1eaa140fe000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required, not cosmetic: the column is NOT NULL and the table
    # already has rows. Everything predating the builder arrived as an uploaded archive.
    op.add_column(
        'workflows',
        sa.Column('source', sa.String(), nullable=False, server_default='manual_upload'),
    )
    op.add_column('workflows', sa.Column('draft_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(
        'fk_workflows_draft_id_workflow_drafts',
        'workflows',
        'workflow_drafts',
        ['draft_id'],
        ['id'],
        # SET NULL, not CASCADE: deleting a draft must not delete the workflow published
        # from it - the workflow simply stops being editable in the builder
        ondelete='SET NULL',
    )
    # the draft -> workflow lookup (WorkflowsRepository.find_by_draft_id /
    # find_all_by_draft_ids) filters on this column; Postgres does not index FKs itself
    op.create_index(op.f('ix_workflows_draft_id'), 'workflows', ['draft_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflows_draft_id'), table_name='workflows')
    op.drop_constraint('fk_workflows_draft_id_workflow_drafts', 'workflows', type_='foreignkey')
    op.drop_column('workflows', 'draft_id')
    op.drop_column('workflows', 'source')
    # ### end Alembic commands ###
