"""add status column to workflows

Revision ID: 896a59bb63ea
Revises: 8e677e689bba
Create Date: 2026-08-15 11:26:09.353093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '896a59bb63ea'
down_revision: Union[str, Sequence[str], None] = '8e677e689bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'workflows',
        sa.Column(
            'status',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default='pending_validation',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'status')
    # ### end Alembic commands ###
