"""add workflows, workflow_steps, and workflow_domains tables

Revision ID: 8e677e689bba
Revises: cb4f0e9d8d39
Create Date: 2026-08-15 10:23:10.393456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8e677e689bba'
down_revision: Union[str, Sequence[str], None] = 'cb4f0e9d8d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('cwl_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_domains',
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workflow_id', 'domain')
    )
    op.create_table('workflow_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('step_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=True),
    sa.Column('match_status', sa.String(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_steps')
    op.drop_table('workflow_domains')
    op.drop_table('workflows')
    # ### end Alembic commands ###
