"""create favorites table

Revision ID: cd558eeb5fd4
Revises: 0698c9080d01
Create Date: 2026-08-06 18:35:12.353057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cd558eeb5fd4'
down_revision: Union[str, Sequence[str], None] = '0698c9080d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    # scoped to the component lineage (name), not a single version row - `name` has no
    # unique constraint of its own, so this can't be a real FK; existence is validated
    # in FavoritesService before every write instead
    sa.Column('component_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'component_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
