"""create favorites table

Revision ID: cd558eeb5fd4
Revises: 0698c9080d01
Create Date: 2026-08-06 18:35:12.353057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cd558eeb5fd4'
down_revision: Union[str, Sequence[str], None] = '0698c9080d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    # 'COMPONENT' | 'WORKFLOW' - plain string, matching how every other enum is stored
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    # polymorphic: the component *lineage* name, or a workflow uuid as text. Neither can
    # be a real FK - `components.name` has no unique constraint of its own, and one column
    # can't reference two tables - so existence is validated in FavoritesService before
    # every write and orphans are swept on delete
    sa.Column('entity_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'entity_type', 'entity_ref')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
