"""add format column to parameters

Revision ID: f9618993ab3a
Revises: 48c15fcdf411
Create Date: 2026-08-05 16:27:50.453901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f9618993ab3a'
down_revision: Union[str, Sequence[str], None] = '48c15fcdf411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameters', sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parameters', 'format')
    # ### end Alembic commands ###
